### ISSUE TITLE
How Can I find Google analytics identifier Key?

### ISSUE THREAD

**Issue by Hychhayrith** [ksmandersen/GoogleReporter#14]
Hello. I saw static variable in GoogleReporter.swift named identifierKey in line 65. Can you tell me where can I get that key from Google like you did?

**Comment by ksmandersen** [comment]
You should be able to find the identifier in your Google Analytics tracking code. It starts usually starts with ``GA-``. Heres how to find the tracking code: https://support.google.com/analytics/answer/7476135?hl=en

**Comment by mezhevikin** [comment]
Hi @ksmandersen , @Hychhayrith  !
Actually, Google Analytics already don't let add a new App to get identifier Key. 
Only Firebase, it's too bad :(

**Comment by ksmandersen** [comment]
@Hychhayrith @mezhevikin If you still wish to continue using this library it is possible to do so, by adding the property as a website instead of a mobile app instead. 
![screenshot 2019-02-20 at 11 23 09](https://user-images.githubusercontent.com/178181/53084887-05801e80-3502-11e9-9769-2da89233c665.png)

This will allow you to obtain a tracking id and the analytics data is parsed and used the same way

**Comment by mezhevikin** [comment]
@ksmandersen thk  👍

**Comment by river-littlepay** [comment]
I can't find the the track id now, only api_secret and measure id. Is this library still working now?
